feat: Angular components
tractr/traxion pull request #155
Opened 2021-07-06 02:04 UTC by GlennTractr

2021-07-06 12:32 UTC, ThibautMTL approved these changes

2021-07-06 21:57 UTC, floross approved these changes

2021-07-06 21:57 UTC, floross commented on libs/angular/form/src/lib/item/select/form-select-base.component.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
On multiple file I see disable explicit any but no any type in the code is it normal ?

2021-07-07 13:48 UTC, GlennTractr commented on libs/angular/form/src/lib/item/select/form-select-base.component.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
@floross ici le probleme c'est que le any est dans le extends de la classe. Si je met le disable-next-line juste avant la ligne du any, j'ai prettier qui me la deplace deux lignes plus haut. A moins qu'on puisse faire un disable sur plusieurs ligne, j'ai trouvé que ca comme solution.

2021-07-07 14:32 UTC, floross requested changes

2021-07-07 14:32 UTC, floross commented on libs/angular/components/src/lib/select/select-base.component.ts
> +export abstract class SelectBaseComponent<Type extends any>
You can use `SelectBaseComponent<Type>` instead of `SelectBaseComponent<Type extends any>` ?

2021-07-07 14:32 UTC, floross commented on libs/angular/form/src/lib/item/select/checkbox-group/form-checkbox-group.component.ts
> +export class FormCheckboxGroupComponent extends FormSelectBaseComponent<any> {
`FormSelectBaseComponent<any>` should be `FormSelectBaseComponent` and your declaration should take `FormSelectBaseComponent<Type = unknown>` or another default type

2021-07-07 14:32 UTC, floross commented on libs/angular/form/src/lib/item/select/select/form-select.component.ts
> +export class FormSelectComponent extends FormSelectBaseComponent<any> {
Same as before

2021-07-07 14:32 UTC, floross commented on libs/angular/components/src/lib/select/select-base.component.ts
> +export abstract class SelectBaseComponent<Type extends any>
Or if you want a default you can use `SelectBaseComponent<Type = unknown>`

2021-07-07 14:33 UTC, floross commented on libs/angular/form/src/lib/item/select/form-select-base.component.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
Le mieux est de changer la declaration de ta classe permettant d'accepter un default. au lieu de faire un `extends any` tu peux faire un `= unknowm` ou un autre default type comme `Record<string, unknown>`

2021-07-07 15:19 UTC, floross approved these changes

2021-07-07 17:15 UTC, merged