feat: add angular authentication package to the stack
tractr/traxion pull request #156
Opened 2021-07-06 15:11 UTC by GlennTractr

2021-07-06 15:42 UTC, floross requested changes

2021-07-06 15:42 UTC, floross commented on libs/angular/authentification/README.md
> +        appVersion: '1',
Est ce que appCode et appVersion sont required ? Car le back n'a aucune version ni code particulier

2021-07-06 15:42 UTC, floross commented on libs/angular/authentification/src/lib/authentification-for-root.interface.ts
> +export interface AuthentificationEnvironmentInterface {
Est ce que c'est pas au final plus des options que des environnements ?

2021-07-06 15:42 UTC, floross commented on libs/angular/authentification/src/lib/authentification.module.ts
> +          provide: 'environment',
Il faudrait creer une constant `const ANGULAR_AUTHENTICATION_OPTIONS: string = 'ANGULAR_AUTHENTICATION_OPTIONS'` qui devrait etre utiliser lors de l'injection. Tu peux regarder cote backend comment c'est fait c'est exactement la meme chose

2021-07-06 15:42 UTC, floross commented on libs/angular/authentification/src/lib/components/login/login.component.ts
> +    @Inject('environment')
A utiliser la constant creer plus tot

2021-07-06 15:42 UTC, floross commented on libs/angular/authentification/src/lib/components/login/login.component.ts
> +    console.log('error sign in', err);
Est ce que l'on veut vraiment juste console log ici ? Si oui utiliser `console.error` et enlever le eslint disable

2021-07-06 15:42 UTC, floross commented on libs/angular/authentification/src/lib/components/logout/logout.component.ts
> +    @Inject('environment')
Meme remarque a utiliser la constant, je ne remet pas de commentaire dans la suite cela va etre la meme chose de partout ou tu utilises `@Inject('environment)`

2021-07-06 15:42 UTC, floross commented on libs/angular/authentification/src/lib/components/logout/logout.component.ts
> +    @Inject('environment')
De plus je pense que tu peux renommer `environment` par `authenticationOptions`

2021-07-06 15:42 UTC, floross commented on libs/angular/authentification/src/lib/directives/base-connected.directive.ts
> +    private templateRef: TemplateRef<any>,
A remplace par `TemplateRef<unknown>` marche ?

2021-07-06 15:42 UTC, floross commented on libs/angular/authentification/src/lib/services/session.service.ts
> +    console.log('todo: handle login error', e);
ErrorService est dans le angular tools deja ?

2021-07-06 15:42 UTC, floross commented on libs/angular/authentification/src/lib/services/session.service.ts
> +          resolve(self);
Si il y a une erreur on risque d'etre bloquer a l'infinit.

Est ce que ca aurait ete pas mieux de tout faire en reactif ?

2021-07-06 15:42 UTC, floross commented on libs/nestjs/authentication/src/authentication.module.ts
> +        { provide: APP_GUARD, useClass: JwtGlobalAuthGuard },
On ne doit pas mettre le `APP_GUARD` ici mais dans l'app, dans le futur on pourra penser a creer autre chose que le `JwtGlobalAuthGuard`

2021-07-06 15:42 UTC, floross commented on workspace.json
> +                  "maximumError": "5mb",
Ca me parait beaucoup 5mb non ?

2021-07-06 17:54 UTC, GlennTractr commented on libs/angular/authentification/README.md
> +        appVersion: '1',
@floross Actuellement elles sont utilisé dans le ErrorService. Si je me trompe pas ca avait pour but de les mettre en Tag dans le Kibana. 

J'ai créer une issue pour faire un refacto du ErrorService (https://github.com/tractr/stack/issues/157)

2021-07-07 18:17 UTC, floross requested changes

2021-07-07 18:17 UTC, floross commented on libs/angular/authentification/src/lib/authentification-for-root.interface.ts
> +export enum AuthentificationForRootEnum {
Je pense qu'on devrait suivre la [doc d'angular](https://angular.io/guide/dependency-injection-providers#using-an-injectiontoken-object) pour les token des providers: 

```ts
import { InjectionToken } from '@angular/core';

export const AUTHENTICATION_OPTIONS = new InjectionToken<AuthentificationOptionsInterface>('authentication.options');
```

2021-07-07 18:17 UTC, floross commented on libs/angular/authentification/src/lib/authentification-for-root.interface.ts
>  }
```ts
export interface AuthentificationForRootInterface {
  options: Partial<AuthentificationOptionsInterface>;
}
```

2021-07-07 18:17 UTC, floross commented on libs/angular/authentification/src/lib/authentification.module.ts
> +      overide[AuthentificationForRootEnum.options],
`override.options`

2021-07-07 18:17 UTC, floross commented on libs/angular/authentification/src/lib/authentification.module.ts
> +          provide: AuthentificationForRootEnum.options,
`provide: AUTHENTICATION_OPTIONS`

2021-07-07 18:17 UTC, floross commented on libs/angular/authentification/src/lib/components/login/login.component.ts
> +    @Inject(AuthentificationForRootEnum.options)
`@Inject(AUTHENTICATION_OPTIONS)`

2021-07-12 00:02 UTC, floross approved these changes

2021-07-12 00:02 UTC, merged