feat: add package hapify-rest-templates-dtos
tractr/traxion pull request #43
Opened 2021-03-26 17:57 UTC by maxmousse

2021-03-26 18:06 UTC, GlennTractr approved these changes
@maxmousse a part mon commentaire, ca me semble pas mal.

2021-03-26 18:06 UTC, GlennTractr commented on packages/hapify-templates-rest-dtos/hapify/src/generated/rest-dtos/__kebab__/__kebab__-count-query.dto.ts.hpf
> +
@maxmousse a ligne entre chaque decorateu est supprimer par le prettier? Si non ca serais meilleur de supprimer la ligne entre chaque pour rendre le code generé plus lisible.

2021-03-26 18:11 UTC, floross requested changes

2021-03-26 18:11 UTC, floross commented on packages/hapify-templates-rest-dtos/CHANGELOG.md
> +# @tractr/hapify-templates-nestjs-models-rest [1.1.0](https://github.com/tractr/stack/compare/@tractr/hapify-templates-nestjs-models-rest@1.0.0...@tractr/hapify-templates-nestjs-models-rest@1.1.0) (2
Remove all line extract from other packages

2021-03-26 18:11 UTC, floross commented on packages/hapify-templates-rest-dtos/package.json
> +    "@tractr/hapify-templates-nestjs-models-common": "1.1.0",
needed ?

2021-03-26 18:33 UTC, maxmousse commented on packages/hapify-templates-rest-dtos/hapify/src/generated/rest-dtos/__kebab__/__kebab__-count-query.dto.ts.hpf
> +
Yes le prettier rend ça tout beau tout beau!

2021-03-29 19:23 UTC, maxmousse commented
This PR is not relevant anymore due to dtos templates being hosted in hapify-templates-rest-client package

2021-03-29 19:23 UTC, closed without merging