feat: add new lib for generate client conf and put in session storage
tractr/traxion pull request #536
Opened 2022-12-02 13:53 UTC by labuchTractr

2022-12-19 18:41 UTC, maxmousse commented
@labuchTractr On va attendre la validation et le retour de @floross pour merger celle là: elle est un peu touchy et elle introduit des breaking changes.

2023-01-17 09:56 UTC, floross commented on apps/admin/src/environments/environment.default.ts
> +export function getConfig(appConfig: AppConfig): AppConfig {
I don't think it is an AppConfig that you take in params but more an AdminEnv

2023-01-17 10:10 UTC, floross requested changes
You got a comment on AppConfig in the admin app. Except this part all is good for me. I'll put the changes to do in the next migration

2023-01-17 16:57 UTC, labuchTractr commented on apps/admin/src/environments/environment.default.ts
> +export function getConfig(appConfig: AppConfig): AppConfig {
you'r right  but it's curious that TS did'nt yell at me

2023-01-27 08:28 UTC, floross approved these changes

2023-01-27 08:55 UTC, merged