feat: add a filter for unauthenticated response
tractr/traxion pull request #550
Opened 2023-01-13 19:53 UTC by labuchTractr

2023-01-16 20:57 UTC, GlennTractr approved these changes

2023-01-17 08:16 UTC, floross requested changes

2023-01-17 08:16 UTC, floross commented on libs/nestjs/authentication/src/authentication.module.ts
> +import { UnAuthorizedExceptionFilter } from './filters';
`UnAuthorizedExceptionFilter` should be `UnauthorizedException` without the capital `A`

2023-01-17 08:16 UTC, floross commented on libs/nestjs/authentication/src/filters/unauthorized.filter.ts
> +    });
We should mimic the Error from nestjs Exception from https://docs.nestjs.com/exception-filters#built-in-http-exceptions. I know the exception exemple add timestamp and path but we should keep the json from the original error:

```json
{
  "message": "Something bad happened",
  "error": "Some error description",
  "statusCode": 400,
}
```

2023-01-17 08:17 UTC, floross commented on libs/nestjs/authentication/src/filters/unauthorized.filter.ts
> +    });
Probably you want to pass by the error message and the error form the original error

2023-01-17 16:36 UTC, labuchTractr commented on libs/nestjs/authentication/src/filters/unauthorized.filter.ts
> +    });
I but the name and the message from the exception in the body there is still the message error in the response as well

2023-01-19 07:31 UTC, floross approved these changes

2023-02-06 16:29 UTC, merged