Stak 740/generator nestjs service module
tractr/traxion pull request #582
Opened 2023-02-27 03:53 UTC by Mickael-Martos

2023-02-27 08:41 UTC, floross commented
Can you rename this PR by following the conventional commit format ?

2023-02-27 09:31 UTC, floross commented on libs/generated/nestjs-models-common/ModelsServicesOptions.ts
> +export * from "'./ModelsServicesOptions.ts'";
I will not review the nestjs-models-common. Can you create another lib nestjs-service where we will put all our generated files.

I will review the generated files but we should excludes them before merging this PR

2023-02-27 09:31 UTC, floross commented on libs/generated/nestjs-models-common/modelsservicesoptions_ts
> +export * from "./index";
this file should be removed

2023-02-27 09:31 UTC, floross commented on libs/generated/nestjs-models-common/src/generate.ts
> +    // stringField('password', { isPassword: true }),
You can use `stringField('password', { isEncrypted: true });` for now and add a todo to use `passwordField()`

2023-02-27 09:31 UTC, floross commented on libs/generated/nestjs-models-common/src/ts-morph-generated/models-services.module-definition.ts
> +  )
Add a todo to update this code by using our internal trxn helpers that will be merge this week into main

2023-02-27 09:31 UTC, floross commented on libs/generated/nestjs-models-common/src/ts-morph-generated/services/role-database.service.ts
> +export const RoleDatabaseServiceInject = [DATABASE_SERVICE];
I think we not need this file anymore because we are using DATABASE_SERVICE directly

2023-02-27 09:31 UTC, floross commented on libs/generated/nestjs-models-common/src/ts-morph-generated/constants/role-model.constants.ts
> +export const ROLE_DATABASE_SERVICE = 'ROLE_DATABASE_SERVICE';
I am not sure if we still need the `_DATABASE_SERVICE` token

2023-02-27 09:31 UTC, floross commented on libs/generated/nestjs-models-common/src/ts-morph-generated/services/role.service.ts
> +   */
The comments are weirdly formated

2023-02-27 09:31 UTC, floross commented on libs/generated/nestjs-models-common/src/ts-morph-generated/services/role.service.ts
> +  }
We should create a `<model>-default.service.ts` that expose a <Model>DefaultService to manage the default value of the models and inject the <Model>DefaultService in this service. The service could expose the default value with getters: `get createdAt() { return new Date(); }`

2023-02-27 09:31 UTC, floross commented on libs/generated/nestjs-models-common/src/ts-morph-generated/services/user-database.service.ts
> +export const UserDatabaseServiceInject = [DATABASE_SERVICE];
Same here not sure that we still use this

2023-02-27 09:31 UTC, floross commented on libs/hapify/generators/nestjs-services/README.md
> +[ESLint](https://eslint.org/).
We should had more documentation on how it works

2023-02-27 09:31 UTC, floross commented on libs/hapify/generators/nestjs-services/src/index.ts
> +export * from './lib/generate';
Can you remove the lib folder ?

2023-02-27 09:31 UTC, floross commented on libs/hapify/generators/nestjs-services/src/lib/generators/interface/interface.generator.ts
> +    name: 'ModelsServicesOptions',
ModelsServiceModuleOptions ?

2023-03-02 16:57 UTC, Mickael-Martos commented on libs/generated/nestjs-models-common/src/ts-morph-generated/services/role-database.service.ts
> +export const RoleDatabaseServiceInject = [DATABASE_SERVICE];
done

2023-03-02 16:57 UTC, Mickael-Martos commented on libs/generated/nestjs-models-common/src/ts-morph-generated/models-services.module-definition.ts
> +  )
done

2023-03-02 16:57 UTC, Mickael-Martos commented on libs/generated/nestjs-models-common/src/generate.ts
> +    // stringField('password', { isPassword: true }),
done

2023-03-08 15:59 UTC, floross requested changes

2023-03-08 15:59 UTC, floross commented on config.json
> +"fhdhdf"
A supprimer

2023-03-08 15:59 UTC, floross commented on libs/generated/nestjs-models-common/src/generate.ts
> +hapifyNestjsServicesGenerator(project, schema, config);
Fichier à supprimer

2023-03-08 15:59 UTC, floross commented on libs/generated/nestjs-models-common/src/ts-morph-generate/constants/answer-model.constants.ts
> +export const ANSWER_DATABASE_SERVICE = 'ANSWER_DATABASE_SERVICE';
Dans l'idée après cette review il faudra supprimer le dossier `ts-morph-generate`

Sur ces lignes il faut supprimer le token `_DATABASE_SERVICE` ce n'est plus utilisé dans les services

2023-03-08 15:59 UTC, floross commented on libs/generated/nestjs-models-common/src/ts-morph-generate/constants/answer-model.constants.ts
> +export const ANSWER_DATABASE_SERVICE = 'ANSWER_DATABASE_SERVICE';
Ce commentaire vaut pour tous les fichiers `-model.constants.ts`

2023-03-08 15:59 UTC, floross commented on libs/generated/nestjs-models-common/src/ts-morph-generate/constants/answer-model.constants.ts
> +export const ANSWER_DATABASE_SERVICE = 'ANSWER_DATABASE_SERVICE';
A rajouter ` as const;` a la fin de `_SERVICE`,

```ts
export const ANSWER_SERVICE = 'ANSWER_SERVICE' as const;
```

2023-03-08 15:59 UTC, floross commented on libs/generated/nestjs-models-common/src/ts-morph-generate/interfaces/models-services.interface.ts
> +    prismaClient?: PrismaClient;
On va configurer le PrismaSerivce via le setExtra, remove this line

2023-03-08 15:59 UTC, floross commented on libs/generated/nestjs-models-common/src/ts-morph-generate/models-services.module-definition.ts
> +                    }),  //TODO: make use of internal trxn helpers
Il faut utiliser les helpers provenant de nestjs-core, prendre exemple sur le UserModule et utiliser `PrismaService` de nestjs-database a la place du USER_SERVICE token

2023-03-08 15:59 UTC, floross commented on libs/generated/nestjs-models-common/src/ts-morph-generate/services/answer-defaults.service.ts
> +export class AnswerService {
AnserwerDefaultService

2023-03-08 15:59 UTC, floross commented on libs/generated/nestjs-models-common/src/ts-morph-generate/services/answer.service.ts
> +    constructor(@Inject(DATABASE_SERVICE) private readonly prismaClient: PrismaClient) {
A remplacer:

```ts
constructor(private readonly prismaClient: PrismaService) {}
```

2023-03-08 15:59 UTC, floross commented on libs/generated/nestjs-models-common/src/ts-morph-generate/services/answer.service.ts
> +    constructor(@Inject(DATABASE_SERVICE) private readonly prismaClient: PrismaClient) {
PrismaService vient de nestjs-database

2023-03-08 15:59 UTC, floross commented on libs/generated/prisma/config.json
> +"fhdhdf"
A supprimer

2023-03-08 15:59 UTC, floross commented on libs/generated/nestjs-models-common/src/ts-morph-generate/providers/user-model.providers.ts
> +export const USER_SERVICES_PROVIDERS: Provider[] = [
A remplacer par:

```ts
export const USER_SERVICES_PROVIDERS: Provider[] = [
  UserService,
  { provide: USER_SERVICE, useExisting: UserService },
  UserDefaultService,
  { provide: USER_DEFAULT_SERVICE, useExisting: UserDefaultService },
```

2023-03-08 15:59 UTC, floross commented on libs/generated/nestjs-models-common/src/ts-morph-generate/providers/user-model.providers.ts
> +export const USER_SERVICES_PROVIDERS: Provider[] = [
Il faut penser a ajouter les import et a creer les constants

2023-03-08 19:26 UTC, Mickael-Martos commented on libs/generated/nestjs-models-common/src/ts-morph-generate/services/answer-defaults.service.ts
> +export class AnswerService {
done

2023-03-08 19:53 UTC, Mickael-Martos commented on libs/generated/nestjs-models-common/src/ts-morph-generate/services/answer.service.ts
> +    constructor(@Inject(DATABASE_SERVICE) private readonly prismaClient: PrismaClient) {
done

2023-03-08 19:53 UTC, Mickael-Martos commented on libs/generated/prisma/config.json
> +"fhdhdf"
done

2023-03-08 20:00 UTC, Mickael-Martos commented on libs/generated/nestjs-models-common/src/ts-morph-generate/providers/user-model.providers.ts
> +export const USER_SERVICES_PROVIDERS: Provider[] = [
done

2023-03-08 20:09 UTC, Mickael-Martos commented on libs/generated/nestjs-models-common/src/generate.ts
> +hapifyNestjsServicesGenerator(project, schema, config);
done

2023-03-08 20:09 UTC, Mickael-Martos commented on config.json
> +"fhdhdf"
done

2023-03-08 20:12 UTC, Mickael-Martos commented on libs/generated/nestjs-models-common/src/ts-morph-generate/constants/answer-model.constants.ts
> +export const ANSWER_DATABASE_SERVICE = 'ANSWER_DATABASE_SERVICE';
done

2023-03-08 22:29 UTC, Mickael-Martos commented on libs/generated/nestjs-models-common/src/ts-morph-generate/models-services.module-definition.ts
> +                    }),  //TODO: make use of internal trxn helpers
done

2023-03-08 22:29 UTC, Mickael-Martos commented on libs/generated/nestjs-models-common/src/ts-morph-generate/interfaces/models-services.interface.ts
> +    prismaClient?: PrismaClient;
done

2023-03-09 15:55 UTC, maxmousse commented on libs/hapify/generators/nestjs-services/src/generators/module/module.generator.ts
> +    overwrite: true,
I don't think we should use the 'overwrite' flag. It's probably better to let the createSourceFile throw an error if a file already exists, as its probably synonim of something going wrong.

2023-03-09 15:55 UTC, maxmousse commented on libs/hapify/core/src/lib/hapify-core.spec.ts
> +describe('hapifyCore', () => {
Those files can be removed. I think they have been reintroduced during the rebase by error

2023-03-09 15:55 UTC, maxmousse commented on libs/hapify/core/src/lib/hapify-core.ts
> +export function hapifyCore(): string {
Those files can be removed. I think they have been reintroduced during the rebase by error

2023-03-09 15:55 UTC, maxmousse commented on libs/hapify/generators/nestjs-services/src/generate.ts
> +  // project.saveSync();
This can be removed as it's the prisma generator responsability to touch the disk

2023-03-09 15:55 UTC, maxmousse commented on libs/hapify/generators/nestjs-services/src/generators/interface/interface.generator.ts
> +  sourceFile.addInterface({
To validate with @floross, but I am not sure the config interface is necessary anymore, no ? The module only need to have access to the database module that will be imported in the setExtra part  ?

2023-03-09 15:55 UTC, maxmousse commented on libs/hapify/generators/nestjs-services/src/generators/provider/providers.generator.ts
> +  const existingImport = servicesProviderSourceFile
Could'nt this ben done in the function that generates the imports ?

2023-03-09 15:55 UTC, maxmousse commented on libs/hapify/generators/nestjs-services/src/generators/service/constructor.generator.ts
> +        // decorators: [
Those comments can be removed befor merge =)

2023-03-09 15:55 UTC, maxmousse commented on libs/hapify/generators/nestjs-services/src/generators/service/imports.generator.ts
> +      namedImports: [{ name: `DATABASE_SERVICE` }],
I think this import is not used. Maybe you should disable the 'fixImport' clause in the generator for the review, or it wil hide some unused imports.

2023-03-09 15:55 UTC, maxmousse commented on libs/hapify/generators/nestjs-services/src/generators/service/index.generator.ts
> +    overwrite: true,
Same remark as before, I'm not sure we should use the overwrite flag.

2023-03-09 15:55 UTC, maxmousse commented on libs/hapify/generators/nestjs-services/src/generators/service/service-defaults.generator.ts
> +    overwrite: true,
Same remark

2023-03-09 15:55 UTC, maxmousse commented on libs/hapify/generators/nestjs-services/src/generators/service/service.generator.ts
> +    overwrite: true,
Same remark here

2023-03-09 19:25 UTC, Mickael-Martos commented on libs/hapify/core/src/lib/hapify-core.spec.ts
> +describe('hapifyCore', () => {
done

2023-03-09 19:25 UTC, Mickael-Martos commented on libs/hapify/generators/nestjs-services/src/generators/module/module.generator.ts
> +    overwrite: true,
done

2023-03-09 19:26 UTC, Mickael-Martos commented on libs/hapify/core/src/lib/hapify-core.ts
> +export function hapifyCore(): string {
done

2023-03-09 19:26 UTC, Mickael-Martos commented on libs/hapify/generators/nestjs-services/src/generate.ts
> +  // project.saveSync();
done

2023-03-09 19:29 UTC, Mickael-Martos commented on libs/hapify/generators/nestjs-services/src/generators/interface/interface.generator.ts
> +  sourceFile.addInterface({
done

2023-03-09 19:30 UTC, Mickael-Martos commented on libs/hapify/generators/nestjs-services/src/generators/service/constructor.generator.ts
> +        // decorators: [
done

2023-03-09 20:13 UTC, merged