Stak 270/clean package file storage
tractr/traxion pull request #583
Opened 2023-02-27 03:55 UTC by Mickael-Martos

2023-02-27 08:27 UTC, floross commented
@Mickael-Martos can you update the title of your PR to match the conventional commit format ?

2023-02-27 08:40 UTC, floross requested changes

2023-02-27 08:40 UTC, floross commented on libs/nestjs/file-storage/src/configs/file-storage-configuration.ts
> +import {
Can you rename this file in `file-storage.config.ts` ?

2023-02-27 08:40 UTC, floross commented on libs/nestjs/file-storage/src/interfaces/file-storage-configuration-private.interface.ts
> +export interface FileStorageConfigurationPrivate extends MinioClientOptions {
We should name this `FileStoragePrivateConfiguration` or `FileStoragePrivateConfig` instead

2023-02-27 08:40 UTC, floross commented on libs/nestjs/file-storage/src/interfaces/file-storage-configuration-public.interface.ts
>    /**
We should name this `FileStoragePublicConfiguration` or `FileStoragePublicConfig` instead

2023-02-27 08:40 UTC, floross commented on libs/nestjs/file-storage/src/configs/index.ts
> +export * from './file-storage-configuration';
You missed a newline at the end of file

2023-02-27 08:40 UTC, floross commented on libs/nestjs/file-storage/src/file-storage.module-definition.ts
> +
You have two newline in a row you can delete one

2023-02-27 08:40 UTC, floross commented on libs/nestjs/file-storage/src/file-storage.module.spec.ts
> +    // const fileStorageModule: TestingModule;
You should remove this lines if not used

2023-02-27 08:40 UTC, floross commented on libs/nestjs/file-storage/src/file-storage.module.ts
> +  imports: [ConsoleModule],
Should not import ConsoleModule, we should get rid of the cli part of this module

2023-02-27 08:40 UTC, floross commented on libs/nestjs/file-storage/src/interfaces/index.ts
> +export * from './file-storage-configuration-private.interface';
```ts
export * from './file-storage-configuration-public.interface';
export * from './file-storage-configuration-private.interface';
```
Should be renamed:
```ts
export * from './file-storage-public-configuration.interface';
export * from './file-storage-private-configuration.interface';
```

2023-02-27 08:40 UTC, floross commented on libs/nestjs/file-storage/src/services/file-storage.service.spec.ts
> +      // const result =  fileStorageService.getPresignedUploadUrl(fileMimeType, fileSize);
Should be removed if not used

2023-02-27 08:40 UTC, floross commented on libs/nestjs/file-storage/src/services/file-storage.service.spec.ts
> +  // it('should generate presigned url to upload new file', async () => {
Did you finish the tests ?

2023-03-09 02:07 UTC, Mickael-Martos commented on libs/nestjs/file-storage/src/file-storage.module-definition.ts
> +
I have linting issues when removing any of them (need new line between import group and need new line after import if not followed by another import)

2023-03-13 20:24 UTC, maxmousse approved these changes

2023-03-14 15:12 UTC, floross approved these changes

2023-03-14 15:14 UTC, merged